import { useState, useEffect, useRef } from "react";
import { Phone, MapPin, Facebook, MessageCircle, ChevronDown, Fish, Star, Package, Truck, ShoppingBag, Clock, Shield } from "lucide-react";
import AOS from "aos";
import "aos/dist/aos.css";


// ─── TRANSLATIONS ───────────────────────────────────────────────────────────
const T = {
  th: {
    nav_products: "สินค้า",
    nav_wholesale: "ขายส่ง",
    nav_location: "ที่ตั้งร้าน",
    nav_contact: "ติดต่อ",
    nav_chat: "ทักแชท LINE",
    hero_badge: "ร้านปลากัดครบวงจร",
    hero_h1_1: "ปลากัด",
    hero_h1_2: "สวยงาม",
    hero_h1_3: "คัดเกรด",
    hero_sub: "เราคือผู้เพาะเลี้ยงปลากัดมาตรฐาน ทั้งขายปลีก ขายส่ง และมีปลากัดหลากหลายสายพันธุ์ให้เลือก พร้อมบริการจัดส่งทั่วประเทศ",
    hero_btn1: "ดูสินค้าทั้งหมด",
    hero_btn2: "ติดต่อสอบถาม",
    story_label: "เรื่องราวของเรา",
    story_years: "เพาะพันธุ์มาแล้ว",
    story_h2_1: "จากความหลงใหล",
    story_h2_2: "สู่ธุรกิจปลากัด",
    story_p1: "เราเริ่มต้นจากนักเลี้ยงปลากัดตัวเล็กๆ ที่หลงรักความสวยงามและบุคลิกของปลาชนิดนี้ จนพัฒนาเป็นฟาร์มเพาะพันธุ์มืออาชีพที่คัดสรรสายพันธุ์คุณภาพสูง ทั้งเพื่อการสะสม การประกวด และตลาดปลากัดทั่วประเทศ",
    story_p2: "ปัจจุบันเรามีปลากัด ครอบคลุมหลายสายพันธุ์ยอดนิยม พร้อมระบบการดูแลสุขภาพปลาที่ได้มาตรฐาน ก่อนส่งถึงมือลูกค้าทุกคน",
    products_label: "สินค้าของเรา",
    products_h2_1: "ปลากัดคัดเกรด",
    products_h2_2: "พร้อมขาย",
    products_sub: "ทุกตัวผ่านการคัดเกรดอย่างพิถีพิถัน พร้อมคำแนะนำการเลี้ยงดู",
    products_more: "มีสายพันธุ์อื่นๆ อีกมากในสต็อก · ทักแชทเพื่อดูรายการเพิ่มเติม (ภาพปลามาจากการเจน AI โดยอ้างอิงมาจากปลาจริงๆ)",
    food_label: "อาหารสัตว์น้ำ",
    food_h2_1: "อาหารสด",
    food_h2_2: "คุณภาพดี",
    food_sub: "อาหารสดสำหรับปลากัดและปลาสวยงาม คัดสรรคุณภาพ สดใหม่ทุกวัน",
    btn_order: "สั่งซื้อ",
    ws_label: "สำหรับร้านค้า",
    ws_h2_1: "ขายส่ง",
    ws_h2_2: "ราคาพิเศษ เริ่มต้นที่ตัวละ 30 บาท",
    ws_sub: "เราเปิดรับออร์เดอร์ขายส่งสำหรับร้านค้าปลาสวยงาม ร้านเพ็ทช็อป และนักเพาะพันธุ์ทั่วประเทศ ราคาพิเศษตามปริมาณ พร้อมบริการจัดส่งมาตรฐาน",
    ws_price_label: "ตารางราคาส่ง",
    ws_btn: "ขอใบเสนอราคาส่ง",
    loc_label: "มาเยี่ยมเราได้เลย",
    loc_h2: "ที่ตั้ง",
    loc_h2_2: "ร้าน",
    loc_addr_label: "ที่อยู่ร้าน",
    loc_addr: "167 หมู่ 1 ถ.ผดุงวารีย์, ตำบล วาริชภูมิ อำเภอวาริชภูมิ จังหวัด สกลนคร 47150",
    loc_hours_label: "เวลาทำการ",
    loc_sat: "เสาร์ – อาทิตย์",
    loc_mon: "จันทร์ – ศุกร์",
    loc_note_label: "หมายเหตุ",
    loc_note: "ร้านเปิดทุกวัน วันจันทร์–อาทิตย์ สำหรับการสั่งซื้อออนไลน์ ติดต่อได้ทุกวันผ่าน LINE และ Facebook",
    faq_label: "คำถามที่พบบ่อย",
    faq_h2_1: "ข้อ",
    faq_h2_2: "สงสัย",
    faq_h2_3: "ของคุณ",
    contact_label: "พร้อมให้บริการ",
    contact_h2_1: "ติดต่อ",
    contact_sub: "มีคำถาม ต้องการสั่งซื้อ หรืออยากฝากขาย ทักหาเราได้เลยทุกช่องทาง",
    fb_follow: "phapongbettafarm · ติดตามเราบน Facebook",
    footer_copy: "© 2026 PhapongDesign · ปลากัดคัดเกรด ขายส่ง–ขายปลีก",
    ws_qty: ["20–40 ตัว", "40–60 ตัว", "100+ ตัว"],
    ws_disc: ["ราคาส่งตามสายพันธุ์", "ราคาส่งตามสายพันธุ์", "ราคาส่งตามสายพันธุ์"],
    faq_note_label: "หมายเหตุ",
  },
  en: {
    nav_products: "Products",
    nav_wholesale: "Wholesale",
    nav_location: "Location",
    nav_contact: "Contact",
    nav_chat: "Chat on LINE",
    hero_badge: "Full-Service Betta Farm",
    hero_h1_1: "Premium",
    hero_h1_2: "Betta",
    hero_h1_3: "Fish",
    hero_sub: "We are professional betta breeders offering retail, wholesale, and a wide variety of quality bettas with nationwide shipping.",
    hero_btn1: "View All Products",
    hero_btn2: "Contact Us",
    story_label: "Our Story",
    story_years: "Years Breeding",
    story_h2_1: "From a Passion",
    story_h2_2: "to a Betta Business",
    story_p1: "We started as small hobbyists who fell in love with the beauty and personality of betta fish. Over time, we grew into a professional breeding farm selecting only the highest-quality strains — for collectors, show tanks, and the national betta market.",
    story_p2: "Today we carry a wide range of popular betta varieties. Every fish undergoes a health check before it reaches your hands.",
    products_label: "Our Products",
    products_h2_1: "Grade-Selected Bettas",
    products_h2_2: " Ready to Ship",
    products_sub: "Every fish is carefully graded and comes with care guidance.",
    products_more: "Many more strains in stock · Chat to see the full list (The fish image was generated by AI, based on real fish.)",
    food_label: "Aquatic Food",
    food_h2_1: "Fresh",
    food_h2_2: " Live Food",
    food_sub: "Fresh live food for bettas and ornamental fish — quality-selected, delivered fresh daily.",
    btn_order: "Order",
    ws_label: "For Retailers",
    ws_h2_1: "Wholesale",
    ws_h2_2: "Special Prices from ฿30/fish",
    ws_sub: "We accept wholesale orders from pet shops, ornamental fish stores, and breeders nationwide. Volume pricing available with safe standard packaging.",
    ws_price_label: "Wholesale Pricing",
    ws_btn: "Request a Quote",
    loc_label: "Come Visit Us",
    loc_h2: "",
    loc_h2_2: "Our Location",
    loc_addr_label: "Address",
    loc_addr: "167 Moo 1, Phadung Waree Rd., Warichaphum, Sakon Nakhon 47150, Thailand",
    loc_hours_label: "Business Hours",
    loc_sat: "Sat – Sun",
    loc_mon: "Mon – Fri",
    loc_note_label: "Note",
    loc_note: "Open every day, Mon–Sun. For online orders, contact us anytime via LINE or Facebook.",
    faq_label: "FAQ",
    faq_h2_1: "",
    faq_h2_2: "Frequently",
    faq_h2_3: " Asked Questions",
    contact_label: "Ready to Serve",
    contact_h2_1: "Contact",
    contact_sub: "Have questions, want to order, or interested in wholesale? Reach us through any channel.",
    fb_follow: "phapongbettafarm · Follow us on Facebook",
    footer_copy: "© 2026 PhapongDesign · Premium Bettas, Retail & Wholesale",
    ws_qty: ["20–39 fish", "40–99 fish", "100+ fish"],
    ws_disc: ["Wholesale price by strain", "Wholesale price by strain", "Wholesale price by strain"],
    faq_note_label: "Note",
  },
  zh: {
    nav_products: "产品",
    nav_wholesale: "批发",
    nav_location: "门店地址",
    nav_contact: "联系我们",
    nav_chat: "LINE咨询",
    hero_badge: "一站式斗鱼农场",
    hero_h1_1: "精选",
    hero_h1_2: "斗鱼",
    hero_h1_3: "品质保证",
    hero_sub: "我们是专业斗鱼养殖场，提供零售、批发服务，品种丰富，全国包邮。",
    hero_btn1: "查看所有产品",
    hero_btn2: "联系我们",
    story_label: "我们的故事",
    story_years: "年养殖经验",
    story_h2_1: "从热爱出发",
    story_h2_2: "打造斗鱼事业",
    story_p1: "我们从一群热爱斗鱼的爱好者起步，逐渐发展成专业养殖场，专注培育高品质斗鱼，服务收藏家、比赛爱好者及全国斗鱼市场。",
    story_p2: "目前涵盖所有热门品种，每条鱼均经过健康筛查后才发货，品质有保障。",
    products_label: "我们的产品",
    products_h2_1: "精品斗鱼",
    products_h2_2: "现货发售",
    products_sub: "每条鱼均经严格分级，附带饲养建议。",
    products_more: "库存还有更多品种 · 聊天查看完整列表 (图片由 AI 生成，并以真实斗鱼为参考制作，仅供展示。)",
    food_label: "水族饲料",
    food_h2_1: "新鲜",
    food_h2_2: "活体饲料",
    food_sub: "专为斗鱼和观赏鱼精选的新鲜活体饲料，每日新鲜供应。",
    btn_order: "下单",
    ws_label: "面向商家",
    ws_h2_1: "批发",
    ws_h2_2: "特惠价格，起批价30泰铢/条",
    ws_sub: "我们向观赏鱼店、宠物店及全国繁殖者开放批发订单，批量越多价格越优惠，安全标准包装发货。",
    ws_price_label: "批发价格表",
    ws_btn: "申请报价",
    loc_label: "欢迎来访",
    loc_h2: "",
    loc_h2_2: "门店地址",
    loc_addr_label: "地址",
    loc_addr: "泰国色军府 Warichaphum区 Phadung Waree路167号1村 邮编47150",
    loc_hours_label: "营业时间",
    loc_sat: "周六 – 周日",
    loc_mon: "周一 – 周五",
    loc_note_label: "备注",
    loc_note: "每天营业（周一至周日）。线上订单请随时通过LINE或Facebook联系我们。",
    faq_label: "常见问题",
    faq_h2_1: "",
    faq_h2_2: "常见",
    faq_h2_3: "问题解答",
    contact_label: "随时为您服务",
    contact_h2_1: "联系",
    contact_sub: "有疑问、想下单或洽谈批发？欢迎通过任何渠道联系我们。",
    fb_follow: "phapongbettafarm · 关注我们的Facebook",
    footer_copy: "© 2026 PhapongDesign · 精品斗鱼，零售与批发",
    ws_qty: ["20–39条", "40–99条", "100条以上"],
    ws_disc: ["按品种批发价", "按品种批发价", "按品种批发价"],
    faq_note_label: "备注",
  },
};

const fishProducts = [
  {
    id: 1,
    name: { th: "ปลากัดหูช้างฮาฟมูน", en: "Halfmoon Betta", zh: "半月斗鱼" },
    eng: "Halfmoon Betta",
    price: "100–150",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade A–S",
    desc: {
      th: "ครีบสวยงาม กางเต็ม 180° สีสันสดใส",
      en: "Beautiful fins spread 180°, vibrant solid and multicolor varieties.",
      zh: "鱼鳍优美，可展开180°，颜色鲜艳，有单色和多色可选。",
    },
    img: "/image/image3.png",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
  {
    id: 2,
    name: { th: "ปลากัดหางมงกุฎ", en: "Crowntail Betta", zh: "皇冠尾斗鱼" },
    eng: "Crowntail Betta",
    price: "150–250",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade B–S",
    desc: {
      th: "ครีบแฉกสวย คล้ายมงกุฎ โดดเด่น ดุดัน เลี้ยงง่าย เหมาะสำหรับมือใหม่",
      en: "Spiked fins like a crown, bold and easy to keep — perfect for beginners.",
      zh: "锯齿状鱼鳍形如皇冠，个性突出，易于饲养，适合新手。",
    },
    img: "/image/image5.png",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
  {
    id: 3,
    name: { th: "ปลาป่ามหาชัย", en: "Giant / Wild Betta", zh: "巨型/野生斗鱼" },
    eng: "Giant / Wild Betta",
    price: "100–150",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade A–S+",
    desc: {
      th: "สายพันธุ์หายาก ดุดัน สวยงาม เหมาะสำหรับนักสะสมและการประกวด",
      en: "Rare, fierce, and stunning — ideal for collectors and competitions.",
      zh: "稀有品种，威猛美观，适合收藏家和比赛用途。",
    },
    img: "/image/image6.png",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
  {
    id: 4,
    name: { th: "ปลากัดมัลติคัลเลอร์", en: "Plakat Fighting Betta", zh: "短尾格斗斗鱼" },
    eng: "Plakat Fighting Betta",
    price: "100–150",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade B–A",
    desc: {
      th: "แข็งแกร่ง ทนทาน ครีบสั้น ว่องไว นิยมในการแข่งขันและสายเลี้ยงเพื่อสุขภาพ",
      en: "Tough, agile, short fins — popular for competitions and active keeping.",
      zh: "坚韧灵活，短鳍，深受比赛爱好者和健康养殖者欢迎。",
    },
    img: "/image/image7.png",
   tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
    {
    id: 5,
    name: { th: "ปลากัดกีต้าร์", en: "Guitar Tail Wild Betta", zh: "斗鱼" },
    eng: "Guitar Tail Wild Betta",
    price: "100–150",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade A–S",
    desc: {
      th: "ปลากัดสายป่าหางกีต้าร์ เกล็ดเมทัลลิกโดดเด่น สง่างามไม่เหมือนใคร",
      en: "Rare wild-type betta with an elegant guitar-shaped tail and shimmering metallic scales.",
      zh: "稀有野生斗鱼，拥有独特吉他尾和闪耀金属鳞片。",
    },
    img: "/image/image12.png",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
  {
    id: 6,
    name: { th: "ปลากัดหูช้างทอง", en: "Gold Big Ear Betta", zh: "黄金大耳斗鱼" },
    eng: "Gold Big Ear Betta",
    price: "60–100",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade B–S",
    desc: {
      th: "ปลากัดหูช้างทอง สีทองอร่าม ครีบหูใหญ่ สวยสะดุดตา",
      en: "Brilliant golden body with oversized pectoral fins, graceful and eye-catching.",
      zh: "金黄色鱼身，超大耳鳍，优雅夺目。",
    },
    img: "/image/image13.png",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
  {
    id: 7,
    name: { th: "ปลากัดเบญจรงค์แดง", en: "Peaceful Betta", zh: " 红色斗鱼" },
    eng: "Peaceful Betta",
    price: "100–150",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade A–S+",
    desc: {
      th: "ปลากัดเบญจรงค์แดง สีแดงเข้ม ครีบสมดุล โดดเด่นทุกมุมมอง",
      en: "Deep red coloration with a balanced form, calm yet powerful appearance.",
      zh: "深红色体色，体态均衡，沉稳而充满力量。",
    },
    img: "/image/image14.png",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
  {
    id: 8,
    name: { th: "ปลากัด red dragon", en: "Red Dragon Betta", zh: "红龙斗鱼" },
    eng: "Red Dragon Betta",
    price: "100–150",
    unit: { th: "บาท/ตัว", en: "THB/fish", zh: "泰铢/条" },
    grade: "Grade B–A",
    desc: {
      th: "ปลากัดเรดดราก้อน ลำตัวขาว ครีบแดงสด เอกลักษณ์เหนือระดับ",
      en: "Snow-white body with vivid red fins, a timeless and premium Dragon variety.",
      zh: "雪白鱼身配鲜红鱼鳍，经典高端红龙斗鱼。",
    },
    img: "/image/image15.png",
   tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
];

const foodProducts  = [
  {
    id: 1,
    name: { th: "ไรแดงสด", en: "Fresh Bloodworms", zh: "新鲜红虫" },
    eng: "Fresh Bloodworms",
    price: "20",
    unit: { th: "บาท/ถุง", en: "THB/pack", zh: "泰铢/包" },
    weight: "15 กรัม · 1 ช้อนโต๊ะ",
    desc: {
      th: "ไรแดงสดคุณภาพดี 15 กรัม (1 ช้อนโต๊ะ) อาหารที่ปลากัดชอบที่สุด กระตุ้นการเจริญเติบโตและสีสันสวยงาม",
      en: "Premium fresh bloodworms, 15g (1 tbsp) per pack. Betta's favorite food — boosts growth and color vibrancy.",
      zh: "优质新鲜红虫，每包15克（1汤匙）。斗鱼最爱的食物，促进生长、使体色更鲜艳。",
    },
    img: "/image/image9.png ",
    tag: { th: "ขายดี", en: "Best Seller", zh: "热销" },
    tagColor: "bg-cyan-500",
  },
];

const faqs = {
  th: [
    { q: "สั่งซื้อออนไลน์ได้ไหม?", a: "ได้เลยครับ! ทักแชทผ่าน LINE หรือ Facebook เลือกสายพันธุ์ที่ต้องการ ชำระเงิน และเราจัดส่งให้ภายใน 1–2 วันทำการ" },
    { q: "ส่งต่างจังหวัดได้ไหม? ค่าส่งเท่าไหร่?", a: "ส่งได้ทุกจังหวัดครับ ค่าส่ง 60–120 บาท ขึ้นอยู่กับจำนวนปลาและปลายทาง มีบริการรับเองที่ร้านด้วย" },
    { q: "ซื้อส่งราคาเท่าไหร่?", a: "ราคาส่งเริ่มต้นที่การซื้อ 20 ตัวขึ้นไป เริ่มต้นที่ตัวละ 30 บาท จากราคาปลีก ยิ่งซื้อมากยิ่งได้ราคาดี ติดต่อสอบถามเพื่อรับใบเสนอราคาได้เลย" },
     
  ],
  en: [
    { q: "Can I order online?", a: "Absolutely! Chat with us on LINE or Facebook, pick your strain, pay, and we'll ship within 1–2 business days." },
    { q: "Do you ship nationwide? What are the shipping fees?", a: "We ship to every province. Shipping is 60–120 THB depending on quantity and destination. In-store pickup is also available." },
    { q: "What are the wholesale prices?", a: "Wholesale starts at 20+ fish, from 30 THB off retail per fish. The more you buy, the better the price. Contact us for a quote." },
    
  ],
  zh: [
    { q: "可以在线下单吗？", a: "当然可以！通过LINE或Facebook联系我们，选好品种付款后，我们将在1-2个工作日内发货。" },
    { q: "可以发货到其他省份吗？运费多少？", a: "全国各省均可发货，运费60-120泰铢，根据数量和目的地而定。也可到店自提。" },
    { q: "批发价格是多少？", a: "批发起批20条，每条在零售价基础上优惠30泰铢起。购买越多越优惠，联系我们获取报价单。" },
    
  ],
};

const wholesalePerks = {
  th: [
    { icon: Package, title: "ซื้อขั้นต่ำ 20 ตัว", sub: "ได้ราคาส่งพิเศษ" },
    { icon: Truck, title: "จัดส่งทั่วไทย", sub: "แพ็คกิ่งมาตรฐานปลอดภัย" },
    { icon: Shield, title: "รับประกัน 24 ชม.", sub: "หากปลาเสียระหว่างส่ง" },
    { icon: Star, title: "คัดเกรดพร้อมส่ง", sub: "ตรวจสอบทุกตัวก่อนจัดส่ง" },
  ],
  en: [
    { icon: Package, title: "Min. 20 fish", sub: "Unlock wholesale pricing" },
    { icon: Truck, title: "Ships Nationwide", sub: "Safe standard packaging" },
    { icon: Shield, title: "24hr Guarantee", sub: "Covered if fish dies in transit" },
    { icon: Star, title: "Graded & Ready", sub: "Every fish inspected before ship" },
  ],
  zh: [
    { icon: Package, title: "最低起批20条", sub: "享受批发特价" },
    { icon: Truck, title: "全国配送", sub: "标准安全包装" },
    { icon: Shield, title: "24小时保障", sub: "运输途中死亡包赔" },
    { icon: Star, title: "分级即发", sub: "每条鱼发货前逐一检查" },
  ],
};

const heroVideos = [
  "/video/v1.mp4",  
  "/video/clip2.mp4",
  "https://www.pexels.com/th-th/download/video/37685390/",  
];

type Lang = "th" | "en" | "zh";

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-border rounded-xl overflow-hidden cursor-pointer group" onClick={() => setOpen(!open)}>
      <div className="flex items-center justify-between p-5 bg-secondary/40 hover:bg-secondary/70 transition-colors">
        <span className="font-medium text-foreground text-sm md:text-base">{q}</span>
        <ChevronDown size={18} className={`text-primary flex-shrink-0 transition-transform duration-300 ${open ? "rotate-180" : ""}`} />
      </div>
      {open && (
        <div className="p-5 bg-card text-muted-foreground text-sm leading-relaxed border-t border-border">{a}</div>
      )}
    </div>
  );
}

function TikTokIcon({ size = 22 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
      <path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-2.88 2.5 2.89 2.89 0 0 1-2.89-2.89 2.89 2.89 0 0 1 2.89-2.89c.28 0 .54.04.79.1V9.01a6.28 6.28 0 0 0-.79-.05 6.34 6.34 0 0 0-6.34 6.34 6.34 6.34 0 0 0 6.34 6.34 6.34 6.34 0 0 0 6.33-6.34V8.69a8.18 8.18 0 0 0 4.78 1.52V6.75a4.85 4.85 0 0 1-1.01-.06Z" />
    </svg>
  );
}
function GoldLines() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d")!;
    let raf: number;

    const resize = () => {
      canvas.width = canvas.offsetWidth;
      canvas.height = canvas.offsetHeight;
    };
    setTimeout(resize, 50);
    window.addEventListener("resize", resize);

    const lines = Array.from({ length: 60 }, () => ({
  x: Math.random(),
  y: Math.random(),
  angle: Math.random() * Math.PI * 2,
  speed: 0.0008 + Math.random() * 0.0012,
  length: 0.15 + Math.random() * 0.9,
  angleSpeed: (Math.random() - 0.5) * 0.008,
  alpha: 0.3 + Math.random() * 0.5,
  width: 0.8 + Math.random() * 3.2,
  twinkle: Math.random() * Math.PI * 2,      // phase เริ่มต้นของการกะพริบ
  twinkleSpeed: 0.05 + Math.random() * 0.08, // ความเร็วกะพริบ
}));

const loop = () => {
  const W = canvas.width;
  const H = canvas.height;
  ctx.clearRect(0, 0, W, H);

  for (const l of lines) {
    l.x += Math.cos(l.angle) * l.speed;
    l.y += Math.sin(l.angle) * l.speed;
    l.angle += l.angleSpeed;
    l.twinkle += l.twinkleSpeed; // อัพเดท phase กะพริบ

    if (l.x < -0.3) l.x = 1.3;
    if (l.x > 1.3) l.x = -0.3;
    if (l.y < -0.3) l.y = 1.3;
    if (l.y > 1.3) l.y = -0.3;

    const x2 = l.x * W + Math.cos(l.angle) * l.length * W;
    const y2 = l.y * H + Math.sin(l.angle) * l.length * H;

    // alpha กะพริบตาม sine
    const pulse = 0.5 + 0.5 * Math.sin(l.twinkle);
    const a = l.alpha * pulse;

    // glow
    ctx.beginPath();
    ctx.arc(x2, y2, l.width * 4, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(255,200,40,${a * 0.15})`;
    ctx.fill();

    // จุดหลัก
    ctx.beginPath();
    ctx.arc(x2, y2, l.width * 1.5, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(255,220,60,${a * 0.9})`;
    ctx.fill();

    // ประกาย 4 แฉก (cross) ตอน pulse สูง
    if (pulse > 0.6) {
      const sparkLen = l.width * 6 * pulse;
      const sa = (pulse - 0.6) / 0.4 * a;
      ctx.strokeStyle = `rgba(255,240,150,${sa * 0.8})`;
      ctx.lineWidth = 0.5;
      ctx.lineCap = "round";
      for (let i = 0; i < 4; i++) {
        const a2 = (i / 4) * Math.PI * 2;
        ctx.beginPath();
        ctx.moveTo(x2, y2);
        ctx.lineTo(x2 + Math.cos(a2) * sparkLen, y2 + Math.sin(a2) * sparkLen);
        ctx.stroke();
      }
    }
  }

  raf = requestAnimationFrame(loop);
};
    loop();

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", resize);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="absolute inset-0 w-full h-full pointer-events-none"
      style={{ opacity: 0.6 }}
    />
  );
}

export default function App() {
  const [lang, setLang] = useState<Lang>("th");
  const [videoIdx, setVideoIdx] = useState(0);
  const [activeSlot, setActiveSlot] = useState<0 | 1>(0);
  const videoRefs = [useRef<HTMLVideoElement>(null), useRef<HTMLVideoElement>(null)];
  const t = T[lang];

  useEffect(() => {
    AOS.init({ duration: 700, once: true, easing: "ease-out-cubic", offset: 80 });
    const v = videoRefs[0].current;
    if (v) { v.src = heroVideos[0]; v.load(); v.play().catch(() => {}); }
  }, []);

  const goToVideo = (idx: number) => {
    const next = idx % heroVideos.length;
    const nextSlot: 0 | 1 = activeSlot === 0 ? 1 : 0;
    const nextRef = videoRefs[nextSlot].current;
    if (!nextRef) return;
    nextRef.src = heroVideos[next];
    nextRef.load();
    nextRef.play().catch(() => {});
    setTimeout(() => {
      setActiveSlot(nextSlot);
      setVideoIdx(next);
    }, 100);
  };

  const handleVideoEnded = () => {
    goToVideo((videoIdx + 1) % heroVideos.length);
  };

  const langOptions: { key: Lang; label: string }[] = [
    { key: "th", label: "ไทย" },
    { key: "en", label: "EN" },
    { key: "zh", label: "中文" },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground" style={{ fontFamily: "'Sarabun', 'Noto Sans Thai', sans-serif" }}>

      {/* ── AMBIENT GLOW ─────────────────────────────────────────────── */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        <div className="absolute -top-40 -left-40 w-96 h-96 rounded-full opacity-10" style={{ background: "radial-gradient(circle, #00c8f0 0%, transparent 70%)" }} />
        <div className="absolute top-1/3 -right-32 w-80 h-80 rounded-full opacity-8" style={{ background: "radial-gradient(circle, #e8334a 0%, transparent 70%)" }} />
        <div className="absolute bottom-0 left-1/3 w-72 h-72 rounded-full opacity-6" style={{ background: "radial-gradient(circle, #7c3aed 0%, transparent 70%)" }} />
      </div>
      
      {/* ── FLOATING SOCIAL SIDEBAR ──────────────────────────────────── */}
      <div className="fixed right-3 top-1/2 -translate-y-1/2 z-50 flex flex-col gap-2">
        <a href="https://lin.ee/Sfg540k" target="_blank" rel="noopener noreferrer" title="LINE"
          className="flex items-center justify-center w-10 h-10 md:w-11 md:h-11 rounded-full bg-green-500 text-white shadow-lg transition-transform duration-200 hover:scale-125 active:scale-110">
          <MessageCircle size={20} />
        </a>
        <a href="https://web.facebook.com/profile.php?id=61582597760134" target="_blank" rel="noopener noreferrer" title="Facebook"
          className="flex items-center justify-center w-10 h-10 md:w-11 md:h-11 rounded-full bg-blue-600 text-white shadow-lg transition-transform duration-200 hover:scale-125 active:scale-110">
          <Facebook size={20} />
        </a>
        <a href="https://www.tiktok.com/@mr.chm" target="_blank" rel="noopener noreferrer" title="TikTok"
          className="flex items-center justify-center w-10 h-10 md:w-11 md:h-11 rounded-full bg-neutral-900 text-white shadow-lg transition-transform duration-200 hover:scale-125 active:scale-110">
          <TikTokIcon size={20} />
        </a>
        <a href="tel:+66623699502" title="โทรศัพท์"
          className="flex items-center justify-center w-10 h-10 md:w-11 md:h-11 rounded-full bg-primary text-white shadow-lg transition-transform duration-200 hover:scale-125 active:scale-110">
          <Phone size={20} />
        </a>
      </div>

      {/* ── LANGUAGE SWITCHER ─────────────────────────────────────────── */}
      <div className="fixed top-20 right-14 z-50 flex gap-1 bg-background/80 border border-border backdrop-blur-md rounded-full px-1.5 py-1 shadow-lg">
        {langOptions.map(({ key, label }) => (
          <button key={key} onClick={() => setLang(key)}
            className={`text-xs font-bold px-3 py-1 rounded-full transition-all ${lang === key ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}>
            {label}
          </button>
        ))}
      </div>

      {/* ── NAV ──────────────────────────────────────────────────────── */}
      <nav className="sticky top-0 z-40 border-b border-border backdrop-blur-md bg-background/80">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            
            <span className="text-lg font-bold tracking-wide text-foreground" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              Phapong<span className="text-primary">BettaFarm</span>
            </span>
          </div>
          <div className="hidden md:flex items-center gap-6 text-sm text-muted-foreground">
            <a href="#products" className="hover:text-primary transition-colors">{t.nav_products}</a>
            <a href="#wholesale" className="hover:text-primary transition-colors">{t.nav_wholesale}</a>
            <a href="#location" className="hover:text-primary transition-colors">{t.nav_location}</a>
            <a href="#contact" className="hover:text-primary transition-colors">{t.nav_contact}</a>
          </div>
          <a href="https://lin.ee/Sfg540k"
            className="flex items-center gap-1.5 bg-primary text-primary-foreground text-xs font-semibold px-4 py-2 rounded-full hover:opacity-90 transition-opacity">
            <MessageCircle size={14} />
            {t.nav_chat}
          </a>
        </div>
      </nav>

      {/* ── HERO ─────────────────────────────────────────────────────── */}
      <section className="relative min-h-screen flex items-center overflow-hidden">
        <div className="absolute inset-0">
          {[0, 1].map((slot) => (
            <video key={slot} ref={videoRefs[slot]} autoPlay muted playsInline
              onEnded={slot === activeSlot ? handleVideoEnded : undefined}
              className="absolute inset-0 w-full h-full object-cover"
              style={{ opacity: slot === activeSlot ? 0.4 : 0, transition: "opacity 1s ease-in-out", zIndex: slot === activeSlot ? 1 : 0 }}
            />
          ))}
          <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex gap-2 z-20">
            {heroVideos.map((_, i) => (
              <button key={i} onClick={() => goToVideo(i)}
                className={`h-2 rounded-full transition-all duration-300 ${i === videoIdx ? "bg-primary w-6" : "bg-white/40 w-2"}`} />
            ))}
          </div>
          <div className="absolute inset-0 z-10" style={{ background: "linear-gradient(135deg, #060b18 0%, rgba(6,11,24,0.6) 50%, #060b18 100%)" }} />
        </div>

        <div className="relative z-10 max-w-6xl mx-auto px-4 py-32 grid md:grid-cols-2 gap-12 items-center">
          <div data-aos="fade-right" data-aos-duration="900">
            <div className="inline-flex items-center gap-2 bg-primary/10 border border-primary/30 text-primary text-xs font-semibold px-3 py-1.5 rounded-full mb-6 tracking-widest uppercase">
              <Fish size={12} />
              {t.hero_badge}
            </div>
            <h1 className="text-5xl md:text-7xl font-bold leading-tight mb-4" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              {t.hero_h1_1}<br />
              <span className="text-primary">{t.hero_h1_2}</span><br />
              {t.hero_h1_3}
            </h1>
            <p className="text-muted-foreground text-base md:text-lg leading-relaxed mb-8 max-w-md">{t.hero_sub}</p>
            <div className="flex flex-wrap gap-3">
              <a href="#products" className="bg-primary text-primary-foreground font-semibold px-6 py-3 rounded-full hover:opacity-90 transition-all hover:scale-105 text-sm">
                {t.hero_btn1}
              </a>
              <a href="#contact" className="border border-border text-foreground font-semibold px-6 py-3 rounded-full hover:border-primary hover:text-primary transition-all text-sm">
                {t.hero_btn2}
              </a>
            </div>
          </div>

          <div className="hidden md:block" data-aos="fade-left" data-aos-duration="900" data-aos-delay="200">
            <div className="relative">
              <div className="absolute -inset-4 rounded-3xl opacity-30" style={{ background: "radial-gradient(circle, #00c8f0 0%, transparent 70%)" }} />
              <div className="relative bg-card border border-border rounded-3xl overflow-hidden">
                <img src="/image/image3.png" alt="ปลากัดสวยงาม" className="w-full h-72 object-cover object-center" />
                <div className="p-5">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-semibold text-foreground">
                      {lang === "zh" ? "半月斗鱼" : lang === "en" ? "Halfmoon Betta" : "ปลากัดหูช้างฮาฟมูน"}
                    </span>
                    <span className="text-primary font-bold text-lg" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>฿ 180</span>
                  </div>
                  <div className="flex gap-1 mb-3">
                    {[...Array(5)].map((_, i) => <Star key={i} size={12} className="text-amber-400 fill-amber-400" />)}
                    <span className="text-xs text-muted-foreground ml-1">(128 {lang === "zh" ? "评价" : lang === "en" ? "reviews" : "รีวิว"})</span>
                  </div>
                  <div className="flex gap-2">
                    <span className="bg-primary/10 text-primary text-xs px-2 py-1 rounded-md">Halfmoon</span>
                    <span className="bg-accent/10 text-accent text-xs px-2 py-1 rounded-md">Grade S</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── STORY ────────────────────────────────────────────────────── */}
      <section id="STORY" className="relative overflow-hidden py-20 bg-[#08111D]" > <GoldLines />
      
        <div className="max-w-6xl mx-auto px-4">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div className="relative" data-aos="fade-right">
              <div className="grid grid-cols-2 gap-3">
                <img src="/image/image16.png" className="rounded-2xl w-full h-72 object-cover col-span-2" alt="ฟาร์มปลากัด" />
                <img src="/image/image11.png" className="rounded-2xl w-full h-40 object-cover" alt="ปลากัด" />
                <img src="/image/image4.png" className="rounded-2xl w-full h-40 object-cover" alt="ปลากัด" />
              </div>
            </div>
            <div data-aos="fade-left" data-aos-delay="100">
              <div className="text-primary text-sm font-semibold tracking-widest uppercase mb-3">{t.story_label}</div>
              <h2 className="text-3xl md:text-4xl font-bold mb-5" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
                {t.story_h2_1}<br />
                <span className="text-primary">{t.story_h2_2}</span>
              </h2>
              <p className="text-muted-foreground leading-loose mb-4 text-sm md:text-base">{t.story_p1}</p>
              <p className="text-muted-foreground leading-loose text-sm md:text-base">{t.story_p2}</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── PRODUCTS ─────────────────────────────────────────────────── */}
      <section id="products" className="py-20">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12" data-aos="fade-up">
            <div className="text-primary text-sm font-semibold tracking-widest uppercase mb-3">{t.products_label}</div>
            <h2 className="text-3xl md:text-4xl font-bold" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              {t.products_h2_1}<span className="text-primary">{t.products_h2_2}</span>
            </h2>
            <p className="text-muted-foreground mt-3 text-sm max-w-lg mx-auto">{t.products_sub}</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {fishProducts.map((fish, i) => (
              <div key={fish.id} data-aos="fade-up" data-aos-delay={(i % 4) * 80}
                className="group bg-card border border-border rounded-2xl overflow-hidden hover:border-primary/40 transition-all duration-300 hover:-translate-y-1">
                <div className="relative overflow-hidden">
                  <img src={fish.img} alt={fish.name[lang]} className="w-full h-44 object-cover group-hover:scale-105 transition-transform duration-500" />
                  <div className={`absolute top-3 left-3 ${fish.tagColor} text-white text-xs font-bold px-2.5 py-1 rounded-full`}>{fish.tag[lang]}</div>
                </div>
                <div className="p-4">
                  <div className="text-xs text-muted-foreground mb-0.5">{fish.eng}</div>
                  <h3 className="font-semibold text-sm text-foreground mb-1 leading-snug">{fish.name[lang]}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed mb-3">{fish.desc[lang]}</p>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-primary font-bold text-base" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>฿{fish.price}</div>
                      <div className="text-xs text-muted-foreground">{fish.unit[lang]} · {fish.grade}</div>
                    </div>
                    <a href="#contact" className="bg-primary/10 hover:bg-primary text-primary hover:text-primary-foreground text-xs font-semibold px-3 py-1.5 rounded-full transition-all">
                      {t.btn_order}
                    </a>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="text-center mt-8" data-aos="fade-up" data-aos-delay="400">
            <p className="text-muted-foreground text-sm">{t.products_more}</p>
          </div>
        </div>
      </section>

      {/* ── FOOD SECTION ─────────────────────────────────────────────── */}
      <section id="food" className="py-20">
        
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12" data-aos="fade-up">
            <div className="text-cyan-500 text-sm font-semibold tracking-widest uppercase mb-3">{t.food_label}</div>
            <h2 className="text-3xl md:text-4xl font-bold" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              {t.food_h2_1}<span className="text-cyan-500">{t.food_h2_2}</span>
            </h2>
            <p className="text-muted-foreground mt-3 text-sm max-w-lg mx-auto">{t.food_sub}</p>
          </div>
          <div className="flex justify-center">
            <div className="w-full max-w-sm">
              {foodProducts.map((food, i) => (
                <div key={food.id} data-aos="fade-up" data-aos-delay={i * 80}
                  className="group bg-card border border-border rounded-2xl overflow-hidden hover:border-cyan-500/40 transition-all duration-300 hover:-translate-y-1">
                  <div className="relative overflow-hidden">
                    <img src={food.img} alt={food.name[lang]} className="w-full h-100 object-cover object-centergroup-hover:scale-105 transition-transform duration-500" />
                    <div className={`absolute top-3 left-3 ${food.tagColor} text-white text-xs font-bold px-2.5 py-1 rounded-full`}>{food.tag[lang]}</div>
                    <div className="absolute top-3 right-3 bg-yellow-400 text-black text-xs font-bold px-2 py-0.5 rounded-full">
                      {lang === "zh" ? "活体饲料" : lang === "en" ? "Live Food" : "อาหารสด"}
                    </div>
                  </div>
                  <div className="p-4">
                    <div className="text-xs text-muted-foreground mb-0.5">{food.eng}</div>
                    <h3 className="font-semibold text-sm text-foreground mb-1 leading-snug">{food.name[lang]}</h3>
                    <p className="text-xs text-muted-foreground leading-relaxed mb-1">{food.desc[lang]}</p>
                    <p className="text-xs text-cyan-500/80 mb-3">{food.weight}</p>
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="text-cyan-500 font-bold text-base" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>฿{food.price}</div>
                        <div className="text-xs text-muted-foreground">{food.unit[lang]}</div>
                      </div>
                      <a href="#contact" className="bg-cyan-500/10 hover:bg-cyan-500 text-cyan-500 hover:text-white text-xs font-semibold px-3 py-1.5 rounded-full transition-all">
                        {t.btn_order}
                      </a>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── WHOLESALE ────────────────────────────────────────────────── */}
     <section id="wholesale" className="relative overflow-hidden py-20 bg-secondary/20" > <GoldLines />
 
        <div className="max-w-6xl mx-auto px-4">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div data-aos="fade-right">
              <div className="text-primary text-sm font-semibold tracking-widest uppercase mb-3">{t.ws_label}</div>
              <h2 className="text-3xl md:text-4xl font-bold mb-5" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
                {t.ws_h2_1}<br />
                <span className="text-primary">{t.ws_h2_2}</span>
              </h2>
              <p className="text-muted-foreground leading-loose mb-6 text-sm md:text-base">{t.ws_sub}</p>
              <div className="grid grid-cols-2 gap-4 mb-8">
                {wholesalePerks[lang].map(({ icon: Icon, title, sub }, i) => (
                  <div key={title} data-aos="zoom-in" data-aos-delay={i * 80} className="bg-card border border-border rounded-xl p-4">
                    <Icon size={20} className="text-primary mb-2" />
                    <div className="text-sm font-semibold text-foreground">{title}</div>
                    <div className="text-xs text-muted-foreground mt-0.5">{sub}</div>
                  </div>
                ))}
              </div>
              <div className="bg-primary/10 border border-primary/20 rounded-xl p-5 mb-6" data-aos="fade-up" data-aos-delay="200">
                <div className="text-sm font-semibold text-primary mb-2">{t.ws_price_label}</div>
                <div className="space-y-2">
                  {t.ws_qty.map((qty, i) => (
                    <div key={qty} className="flex justify-between items-center text-sm">
                      <span className="text-muted-foreground">{qty}</span>
                      <span className="text-primary font-bold" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>{t.ws_disc[i]}</span>
                    </div>
                  ))}
                </div>
              </div>
              <a href="#contact" className="inline-flex items-center gap-2 bg-primary text-primary-foreground font-semibold px-6 py-3 rounded-full hover:opacity-90 transition-opacity text-sm">
                <ShoppingBag size={16} />
                {t.ws_btn}
              </a>
            </div>
            <div className="relative" data-aos="fade-left" data-aos-delay="150">
              <img src="/image/image10.png" alt="wholesale betta" className="rounded-2xl w-full h-80 md:h-auto object-cover" />
            </div>
          </div>
        </div>
      </section>

      {/* ── LOCATION ─────────────────────────────────────────────────── */}
     <section id="location" className="relative overflow-hidden py-20 bg-secondary/20"> <GoldLines />
  
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12" data-aos="fade-up">
            <div className="text-primary text-sm font-semibold tracking-widest uppercase mb-3">{t.loc_label}</div>
            <h2 className="text-3xl md:text-4xl font-bold" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              <span className="text-primary">{t.loc_h2}</span>{t.loc_h2_2}
            </h2>
          </div>
          <div className="grid md:grid-cols-2 gap-10 items-start">
            <div className="space-y-5" data-aos="fade-right">
              <div className="bg-card border border-border rounded-xl p-5 flex gap-4">
                <MapPin size={20} className="text-primary flex-shrink-0 mt-0.5" />
                <div>
                  <div className="font-semibold text-sm text-foreground mb-1">{t.loc_addr_label}</div>
                  <div className="text-muted-foreground text-sm leading-relaxed">{t.loc_addr}</div>
                </div>
              </div>
              <div className="bg-card border border-border rounded-xl p-5 flex gap-4">
                <Clock size={20} className="text-primary flex-shrink-0 mt-0.5" />
                <div>
                  <div className="font-semibold text-sm text-foreground mb-1">{t.loc_hours_label}</div>
                  <div className="text-muted-foreground text-sm space-y-1">
                    <div className="flex justify-between gap-8"><span>{t.loc_sat}</span><span className="text-foreground">08:00 – 20:00</span></div>
                    <div className="flex justify-between gap-8"><span>{t.loc_mon}</span><span className="text-foreground">08:00 – 20:00</span></div>
                  </div>
                </div>
              </div>
              <div className="bg-primary/10 border border-primary/20 rounded-xl p-5">
                <div className="text-sm font-semibold text-primary mb-2 flex items-center gap-2">
                  <Star size={14} className="fill-primary" /> {t.loc_note_label}
                </div>
                <p className="text-muted-foreground text-sm leading-relaxed">{t.loc_note}</p>
              </div>
            </div>
            <div className="bg-card border border-border rounded-2xl overflow-hidden h-64 md:h-80 relative" data-aos="fade-left" data-aos-delay="100">
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4325.63925554707!2d103.63680024342418!3d17.27993850929953!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313ced19eba8f64f%3A0x5d7b7352c1d2615!2sphapongbettafarm!5e1!3m2!1sth!2sth!4v1782028907921!5m2!1sth!2sth"
                width="100%" height="100%" style={{ border: 0 }} allowFullScreen loading="lazy"
                referrerPolicy="no-referrer-when-downgrade" title="PhapongBettaFarm Location" className="w-full h-full"
              />
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────────────── */}
      <section className="py-20">
        <div className="max-w-3xl mx-auto px-4">
          <div className="text-center mb-10" data-aos="fade-up">
            <div className="text-primary text-sm font-semibold tracking-widest uppercase mb-3">{t.faq_label}</div>
            <h2 className="text-3xl md:text-4xl font-bold" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              {t.faq_h2_1}<span className="text-primary">{t.faq_h2_2}</span>{t.faq_h2_3}
            </h2>
          </div>
          <div className="space-y-3">
            {faqs[lang].map((faq, i) => (
              <div key={faq.q} data-aos="fade-up" data-aos-delay={i * 80}>
                <FAQItem q={faq.q} a={faq.a} />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CONTACT ──────────────────────────────────────────────────── */}
      <section id="contact" className="py-20 bg-secondary/20">
      
        <div className="max-w-4xl mx-auto px-4 text-center">
          <div data-aos="fade-up">
            <div className="text-primary text-sm font-semibold tracking-widest uppercase mb-3">{t.contact_label}</div>
            <h2 className="text-3xl md:text-4xl font-bold mb-4" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              {t.contact_h2_1}<span className="text-primary"> PhapongBettaFarm</span>
            </h2>
            <p className="text-muted-foreground mb-10 text-sm md:text-base">{t.contact_sub}</p>
          </div>
          <div className="grid sm:grid-cols-4 gap-5 mb-10">
            <a href="https://lin.ee/Sfg540k" data-aos="fade-up" data-aos-delay="0"
              className="group bg-card border border-border hover:border-green-500/50 rounded-2xl p-6 flex flex-col items-center gap-3 transition-all hover:-translate-y-1">
              <div className="w-12 h-12 rounded-full bg-green-500/10 flex items-center justify-center group-hover:bg-green-500/20 transition-colors">
                <MessageCircle size={22} className="text-green-400" />
              </div>
              <div className="text-sm font-semibold text-foreground">LINE</div>
              <div className="text-xs text-muted-foreground">@PhapongBettaFarm</div>
            </a>
            <a href="https://web.facebook.com/profile.php?id=61582597760134" data-aos="fade-up" data-aos-delay="100"
              className="group bg-card border border-border hover:border-blue-500/50 rounded-2xl p-6 flex flex-col items-center gap-3 transition-all hover:-translate-y-1">
              <div className="w-12 h-12 rounded-full bg-blue-500/10 flex items-center justify-center group-hover:bg-blue-500/20 transition-colors">
                <Facebook size={22} className="text-blue-400" />
              </div>
              <div className="text-sm font-semibold text-foreground">Facebook</div>
              <div className="text-xs text-muted-foreground">PhapongBettaFarm</div>
            </a>
            <a href="https://www.tiktok.com/@mr.chm" data-aos="fade-up" data-aos-delay="150"
              className="group bg-card border border-border hover:border-neutral-400/50 rounded-2xl p-6 flex flex-col items-center gap-3 transition-all hover:-translate-y-1">
              <div className="w-12 h-12 rounded-full bg-neutral-500/10 flex items-center justify-center group-hover:bg-neutral-500/20 transition-colors">
                <TikTokIcon size={22} />
              </div>
              <div className="text-sm font-semibold text-foreground">TikTok</div>
              <div className="text-xs text-muted-foreground">PhapongBettaFarm</div>
            </a>
            <a href="tel:+66623699502" data-aos="fade-up" data-aos-delay="200"
              className="group bg-card border border-border hover:border-primary/50 rounded-2xl p-6 flex flex-col items-center gap-3 transition-all hover:-translate-y-1">
              <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                <Phone size={22} className="text-primary" />
              </div>
              <div className="text-sm font-semibold text-foreground">{lang === "zh" ? "电话" : lang === "en" ? "Phone" : "โทรศัพท์"}</div>
              <div className="text-xs text-muted-foreground">062-369-9502</div>
            </a>
          </div>
          <div data-aos="fade-up" data-aos-delay="300">
            <a href="https://web.facebook.com/profile.php?id=61582597760134"
              className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors text-sm">
              <Facebook size={16} />
              {t.fb_follow}
            </a>
          </div>
        </div>
      </section>

      {/* ── FOOTER ───────────────────────────────────────────────────── */}
      <footer className="border-t border-border py-8">
        <div className="max-w-6xl mx-auto px-4 flex flex-col md:flex-row items-center justify-between gap-4">
          
          <div className="flex items-center gap-2">
            <Fish size={18} className="text-primary" />
            <span className="font-bold text-foreground" style={{ fontFamily: "'Chakra Petch', sans-serif" }}>
              Phapong<span className="text-primary">BettaFarm</span>
            </span>
          </div>
          <div className="text-xs text-muted-foreground text-center">{t.footer_copy}</div>
          <div className="flex gap-4 text-xs text-muted-foreground">
            <a href="#products" className="hover:text-primary transition-colors">{t.nav_products}</a>
            <a href="#wholesale" className="hover:text-primary transition-colors">{t.nav_wholesale}</a>
            <a href="#contact" className="hover:text-primary transition-colors">{t.nav_contact}</a>
          </div>
        </div>
      </footer>
    </div>
    
  );
}